name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::277015203181:role/github-actions-fariaspnt-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "fariaspnt-us-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "fariaspnt-us-east-1-terraform-lock"
